create table "public"."roadmap_steps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "step_title" text,
    "step_description" text,
    "necessary_documents" jsonb,
    "esitmated_duration" text
);


alter table "public"."roadmap_steps" enable row level security;

CREATE UNIQUE INDEX roadmap_steps_pkey ON public.roadmap_steps USING btree (id);

alter table "public"."roadmap_steps" add constraint "roadmap_steps_pkey" PRIMARY KEY using index "roadmap_steps_pkey";

alter table "public"."roadmap_steps" add constraint "roadmap_steps_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."roadmap_steps" validate constraint "roadmap_steps_user_id_fkey";

grant delete on table "public"."roadmap_steps" to "anon";

grant insert on table "public"."roadmap_steps" to "anon";

grant references on table "public"."roadmap_steps" to "anon";

grant select on table "public"."roadmap_steps" to "anon";

grant trigger on table "public"."roadmap_steps" to "anon";

grant truncate on table "public"."roadmap_steps" to "anon";

grant update on table "public"."roadmap_steps" to "anon";

grant delete on table "public"."roadmap_steps" to "authenticated";

grant insert on table "public"."roadmap_steps" to "authenticated";

grant references on table "public"."roadmap_steps" to "authenticated";

grant select on table "public"."roadmap_steps" to "authenticated";

grant trigger on table "public"."roadmap_steps" to "authenticated";

grant truncate on table "public"."roadmap_steps" to "authenticated";

grant update on table "public"."roadmap_steps" to "authenticated";

grant delete on table "public"."roadmap_steps" to "service_role";

grant insert on table "public"."roadmap_steps" to "service_role";

grant references on table "public"."roadmap_steps" to "service_role";

grant select on table "public"."roadmap_steps" to "service_role";

grant trigger on table "public"."roadmap_steps" to "service_role";

grant truncate on table "public"."roadmap_steps" to "service_role";

grant update on table "public"."roadmap_steps" to "service_role";


