create table "public"."countries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "iso3" text,
    "iso2" text,
    "numeric_code" numeric,
    "capital" text,
    "currency_name" text,
    "currency_symbol" text,
    "native" text,
    "region" text,
    "subregion" text,
    "subregion_id" text,
    "nationality" text,
    "timezones" text,
    "latitude" text,
    "longitude" text,
    "emoji" text,
    "emojiU" text,
    "phone_code" text,
    "currency" text,
    "region_id" text,
    "tld" text
);


alter table "public"."countries" enable row level security;

alter table "public"."users" add column "email" text;

alter table "public"."users" add column "nationality" bigint;

alter table "public"."users" add column "profile_pic" text;

alter table "public"."users" add column "qualification_id" bigint[];

CREATE UNIQUE INDEX countries_pkey ON public.countries USING btree (id);

alter table "public"."countries" add constraint "countries_pkey" PRIMARY KEY using index "countries_pkey";

grant delete on table "public"."countries" to "anon";

grant insert on table "public"."countries" to "anon";

grant references on table "public"."countries" to "anon";

grant select on table "public"."countries" to "anon";

grant trigger on table "public"."countries" to "anon";

grant truncate on table "public"."countries" to "anon";

grant update on table "public"."countries" to "anon";

grant delete on table "public"."countries" to "authenticated";

grant insert on table "public"."countries" to "authenticated";

grant references on table "public"."countries" to "authenticated";

grant select on table "public"."countries" to "authenticated";

grant trigger on table "public"."countries" to "authenticated";

grant truncate on table "public"."countries" to "authenticated";

grant update on table "public"."countries" to "authenticated";

grant delete on table "public"."countries" to "service_role";

grant insert on table "public"."countries" to "service_role";

grant references on table "public"."countries" to "service_role";

grant select on table "public"."countries" to "service_role";

grant trigger on table "public"."countries" to "service_role";

grant truncate on table "public"."countries" to "service_role";

grant update on table "public"."countries" to "service_role";


