create table "public"."qualifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."qualifications" enable row level security;

CREATE UNIQUE INDEX qualifications_pkey ON public.qualifications USING btree (id);

alter table "public"."qualifications" add constraint "qualifications_pkey" PRIMARY KEY using index "qualifications_pkey";

grant delete on table "public"."qualifications" to "anon";

grant insert on table "public"."qualifications" to "anon";

grant references on table "public"."qualifications" to "anon";

grant select on table "public"."qualifications" to "anon";

grant trigger on table "public"."qualifications" to "anon";

grant truncate on table "public"."qualifications" to "anon";

grant update on table "public"."qualifications" to "anon";

grant delete on table "public"."qualifications" to "authenticated";

grant insert on table "public"."qualifications" to "authenticated";

grant references on table "public"."qualifications" to "authenticated";

grant select on table "public"."qualifications" to "authenticated";

grant trigger on table "public"."qualifications" to "authenticated";

grant truncate on table "public"."qualifications" to "authenticated";

grant update on table "public"."qualifications" to "authenticated";

grant delete on table "public"."qualifications" to "service_role";

grant insert on table "public"."qualifications" to "service_role";

grant references on table "public"."qualifications" to "service_role";

grant select on table "public"."qualifications" to "service_role";

grant trigger on table "public"."qualifications" to "service_role";

grant truncate on table "public"."qualifications" to "service_role";

grant update on table "public"."qualifications" to "service_role";


